name: build docs

on:
  push:
    paths:
      - 'docs/konzept-neue-pcs/**'
  pull_request:
    paths:
      - 'docs/konzept-neue-pcs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: create docs
      run: | 
        cd docs/konzept-neue-pcs
        sh run_pandoc.sh
    
    - name: upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: pdf
        path: |
          docs/konzept-neue-pcs/konzept.de.pdf
          docs/konzept-neue-pcs/konzept.en.pdf
          docs/konzept-neue-pcs/konzept.it.pdf
          
        retention-days: 7  # Keep artifacts for 7 days, modify as needed